// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
	site: 'https://gin.wiki',
	output: 'static',

	integrations: [
		starlight({
			title: 'Gin.wiki',
			favicon: '/favicon.ico',
			logo: {
				src: './src/assets/gin.png',
				alt: 'Gin',
			},
			defaultLocale: 'zh-cn',
			locales: {
				'zh-cn': { label: '简体中文', lang: 'zh-CN' },
				'zh-tw': { label: '繁體中文', lang: 'zh-TW' },
				en: { label: 'English', lang: 'en' },
				ja: { label: '日本語', lang: 'ja' },
				'ko-kr': { label: '한국어', lang: 'ko-KR' },
				es: { label: 'Español', lang: 'es' },
				pt: { label: 'Português', lang: 'pt' },
				ru: { label: 'Russian', lang: 'ru' },
				tr: { label: 'Turkish', lang: 'tr' },
				id: { label: 'Bahasa Indonesia', lang: 'id' },
				fa: { label: 'Persian', lang: 'fa' },
				ar: { label: 'عربي', lang: 'ar' },
			},
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/gin-gonic/gin' },
			],
			editLink: {
				baseUrl: 'https://github.com/gin-gonic/website/edit/master/',
			},
			lastUpdated: true,
			credits: false,
			expressiveCode: {
				themes: ['github-light', 'github-dark'],
			},
			customCss: ['./src/styles/global.css', './src/styles/custom.css'],
			components: {
				SiteTitle: './src/components/SiteTitle.astro',
				Head: './src/components/Head.astro',
				Footer: './src/components/Footer.astro',
			},
			sidebar: [
				{
					label: 'Docs',
					translations: {
						'zh-CN': '文档',
						'zh-TW': '文件',
						ja: 'ドキュメント',
						'ko-KR': '문서',
						es: 'Documentación',
						pt: 'Documentação',
						ru: 'Документация',
						tr: 'Belgeler',
						id: 'Dokumentasi',
						fa: 'مستندات',
						ar: 'المستندات',
					},
					items: [
						{
							label: 'Introduction',
							translations: {
								'zh-CN': '介绍',
								'zh-TW': '介紹',
								ja: 'はじめに',
								'ko-KR': '소개',
								es: 'Introducción',
								pt: 'Introdução',
								ru: 'Введение',
								tr: 'Giriş',
								id: 'Pengantar',
								fa: 'معرفی',
								ar: 'مقدمة',
							},
							slug: 'docs/introduction',
						},
						{
							label: 'Quickstart',
							translations: {
								'zh-CN': '快速开始',
								'zh-TW': '快速開始',
								ja: 'クイックスタート',
								'ko-KR': '빠른 시작',
								es: 'Inicio rápido',
								pt: 'Início rápido',
								ru: 'Быстрый старт',
								tr: 'Hızlı Başlangıç',
								id: 'Mulai Cepat',
								fa: 'شروع سریع',
								ar: 'البداية السريعة',
							},
							slug: 'docs/quickstart',
						},
						{
							label: 'Routing',
							translations: {
								'zh-CN': '路由',
								'zh-TW': '路由',
								ja: 'ルーティング',
								'ko-KR': '라우팅',
								es: 'Enrutamiento',
								pt: 'Roteamento',
								ru: 'Маршрутизация',
								tr: 'Yönlendirme',
								id: 'Routing',
								fa: 'مسیریابی',
								ar: 'التوجيه',
							},
							items: [
								{ slug: 'docs/routing/http-method' },
								{ slug: 'docs/routing/param-in-path' },
								{ slug: 'docs/routing/querystring-param' },
								{ slug: 'docs/routing' },
								{ slug: 'docs/routing/multipart-urlencoded-form' },
								{ slug: 'docs/routing/query-and-post-form' },
								{ slug: 'docs/routing/map-as-querystring-or-postform' },
								{
									label: 'Upload Files',
									translations: {
										'zh-CN': '文件上传',
										'zh-TW': '檔案上傳',
										ja: 'ファイルアップロード',
										'ko-KR': '파일 업로드',
										es: 'Subir archivos',
										pt: 'Upload de arquivos',
										ru: 'Загрузка файлов',
										tr: 'Dosya yükleme',
										id: 'Upload file',
										fa: 'آپلود فایل‌ها',
										ar: 'رفع الملفات',
									},
									items: [
										{ slug: 'docs/routing/upload-file' },
										{ slug: 'docs/routing/upload-file/single-file' },
										{ slug: 'docs/routing/upload-file/multiple-file' },
										{ slug: 'docs/routing/upload-file/limit-bytes' },
									],
								},
								{ slug: 'docs/routing/grouping-routes' },
								{ slug: 'docs/routing/redirects' },
								{ slug: 'docs/routing/api-design' },
							],
						},
						{
							label: 'Binding',
							translations: {
								'zh-CN': '数据绑定',
								'zh-TW': '資料綁定',
								ja: 'バインディング',
								'ko-KR': '바인딩',
								es: 'Vinculación',
								pt: 'Binding',
								ru: 'Привязка данных',
								tr: 'Bağlama',
								id: 'Binding',
								fa: 'اتصال داده',
								ar: 'الربط',
							},
							items: [{ autogenerate: { directory: 'docs/binding' } }],
						},
						{
							label: 'Rendering',
							translations: {
								'zh-CN': '渲染',
								'zh-TW': '渲染',
								ja: 'レンダリング',
								'ko-KR': '렌더링',
								es: 'Renderizado',
								pt: 'Renderização',
								ru: 'Рендеринг',
								tr: 'Render',
								id: 'Rendering',
								fa: 'رندرینگ',
								ar: 'العرض',
							},
							items: [{ autogenerate: { directory: 'docs/rendering' } }],
						},
						{
							label: 'Middleware',
							translations: {
								'zh-CN': '中间件',
								'zh-TW': '中介軟體',
								ja: 'ミドルウェア',
								'ko-KR': '미들웨어',
								es: 'Middleware',
								pt: 'Middleware',
								ru: 'Промежуточное ПО',
								tr: 'Ara Yazılım',
								id: 'Middleware',
								fa: 'میان‌افزار',
								ar: 'البرمجيات الوسيطة',
							},
							items: [{ autogenerate: { directory: 'docs/middleware' } }],
						},
						{
							label: 'Logging',
							translations: {
								'zh-CN': '日志',
								'zh-TW': '日誌',
								ja: 'ロギング',
								'ko-KR': '로깅',
								es: 'Registro',
								pt: 'Logging',
								ru: 'Логирование',
								tr: 'Günlükleme',
								id: 'Logging',
								fa: 'ثبت وقایع',
								ar: 'التسجيل',
							},
							items: [{ autogenerate: { directory: 'docs/logging' } }],
						},
						{
							label: 'Server Configuration',
							translations: {
								'zh-CN': '服务器配置',
								'zh-TW': '伺服器設定',
								ja: 'サーバー設定',
								'ko-KR': '서버 설정',
								es: 'Configuración del servidor',
								pt: 'Configuração do servidor',
								ru: 'Настройка сервера',
								tr: 'Sunucu Yapılandırması',
								id: 'Konfigurasi Server',
								fa: 'پیکربندی سرور',
								ar: 'إعدادات الخادم',
							},
							items: [{ autogenerate: { directory: 'docs/server-config' } }],
						},
						{
							label: 'Testing',
							translations: {
								'zh-CN': '测试',
								'zh-TW': '測試',
								ja: 'テスト',
								'ko-KR': '테스트',
								es: 'Pruebas',
								pt: 'Testes',
								ru: 'Тестирование',
								tr: 'Test',
								id: 'Pengujian',
								fa: 'تست',
								ar: 'الاختبار',
							},
							slug: 'docs/testing',
						},
						{
							label: 'Deployment',
							translations: {
								'zh-CN': '部署',
								'zh-TW': '部署',
								ja: 'デプロイ',
								'ko-KR': '배포',
								es: 'Despliegue',
								pt: 'Implantação',
								ru: 'Развёртывание',
								tr: 'Dağıtım',
								id: 'Deployment',
								fa: 'استقرار',
								ar: 'النشر',
							},
							slug: 'docs/deployment',
						},
						{
							label: 'Build Tags',
							translations: {
								'zh-CN': '构建标签',
								'zh-TW': '建置標籤',
								ja: 'ビルドタグ',
								'ko-KR': '빌드 태그',
								es: 'Etiquetas de compilación',
								pt: 'Tags de build',
								ru: 'Теги сборки',
								tr: 'Derleme Etiketleri',
								id: 'Build Tags',
								fa: 'تگ‌های ساخت',
								ar: 'علامات البناء',
							},
							items: [{ autogenerate: { directory: 'docs/build-tags' } }],
						},
						{
							label: 'Benchmarks',
							translations: {
								'zh-CN': '基准测试',
								'zh-TW': '效能測試',
								ja: 'ベンチマーク',
								'ko-KR': '벤치마크',
								es: 'Rendimiento',
								pt: 'Benchmarks',
								ru: 'Бенчмарки',
								tr: 'Karşılaştırmalar',
								id: 'Benchmark',
								fa: 'معیارها',
								ar: 'اختبارات الأداء',
							},
							slug: 'docs/benchmarks',
						},
						{
							label: 'Learning Resources',
							translations: {
								'zh-CN': '学习资源',
								'zh-TW': '學習資源',
								ja: '学習リソース',
								'ko-KR': '학습 자료',
								es: 'Recursos de aprendizaje',
								pt: 'Recursos de aprendizado',
								ru: 'Учебные ресурсы',
								tr: 'Öğrenme Kaynakları',
								id: 'Sumber Belajar',
								fa: 'منابع آموزشی',
								ar: 'مصادر التعلم',
							},
							slug: 'docs/learning-resources',
						},
						{
							label: 'Users',
							translations: {
								'zh-CN': '用户',
								'zh-TW': '使用者',
								ja: 'ユーザー',
								'ko-KR': '사용자',
								es: 'Usuarios',
								pt: 'Usuários',
								ru: 'Пользователи',
								tr: 'Kullanıcılar',
								id: 'Pengguna',
								fa: 'کاربران',
								ar: 'المستخدمون',
							},
							slug: 'docs/users',
						},
						{
							label: 'FAQ',
							translations: {
								'zh-CN': '常见问题',
								'zh-TW': '常見問題',
								ja: 'よくある質問',
								'ko-KR': '자주 묻는 질문',
								es: 'Preguntas frecuentes',
								pt: 'Perguntas frequentes',
								ru: 'Часто задаваемые вопросы',
								tr: 'SSS',
								id: 'FAQ',
								fa: 'سوالات متداول',
								ar: 'الأسئلة الشائعة',
							},
							items: [{ autogenerate: { directory: 'docs/faq' } }],
						},
					],
				},
				{
					label: 'Blog',
					translations: {
						'zh-CN': '博客',
						'zh-TW': '部落格',
						ja: 'ブログ',
						'ko-KR': '블로그',
						es: 'Blog',
						pt: 'Blog',
						ru: 'Блог',
						tr: 'Blog',
						id: 'Blog',
						fa: 'وبلاگ',
						ar: 'المدونة',
					},
					items: [{ autogenerate: { directory: 'blog' } }],
				},
				{
					label: 'About',
					translations: {
						'zh-CN': '关于',
						'zh-TW': '關於',
						ja: 'このサイトについて',
						'ko-KR': '사이트 소개',
						es: 'Acerca de',
						pt: 'Sobre',
						ru: 'О сайте',
						tr: 'Hakkında',
						id: 'Tentang',
						fa: 'درباره',
						ar: 'حول الموقع',
					},
					slug: 'about',
				},
			],
		}),
		sitemap(),
	],

	vite: {
		plugins: [tailwindcss()],
	},
});
